if (!require("data.table")) {
  install.packages("data.table", dependencies = TRUE)
  library(data.table)
}

if (!require("glmnet")) {
  install.packages("glmnet", dependencies = TRUE)
  library(glmnet)
}

if (!require("ggplot2")) {
  install.packages("ggplot2", dependencies = TRUE)
  library(ggplot2)
}

if (!require("gridExtra")) {
  install.packages("gridExtra", dependencies = TRUE)
  library(gridExtra)
}

# script only looks at the first column of the metadata file (for sample names) and the second column (for the assigned class/group/category/celltype to each sample)
# metadata file must have column names and they could be anything, after reading in metadata file, the two columns are named as "sample_name" and "group"
# An example metadata file:
#Run	type
#SRR8788980	carcinoma
#SRR8788981	melanoma
#SRR8788982	lymphoma
#SRR8788983	carcinoma
#SRR8657060	carcinoma


######################################################
############ INPUT PARAMETERS ########################

args <- commandArgs(trailingOnly = TRUE)
num_bins = as.numeric(args[1])
sample_name_to_id_mapping = args[2]
satc_dump_path = args[3]
satc_dir = args[4]
anchors_file = args[5]
directory = args[6] # example: "/oak/stanford/groups/horence/Roozbeh/NOMAD_10x/runs/CCLE_all/"
metadata_file = args[7] # example: "/oak/stanford/groups/horence/Roozbeh/NOMAD_10x/utility_files/CCLE_metadata_modified.tsv"
run_name = args[8] # the output files and plots will be generated in ${directory}/${run_name}_supervised_metadata
anchor_sample_fraction_cutoff = as.numeric(args[9]) # the cutoff for the minimum fraction of samples for each anchor, suggested 0.4
num_anchors_for_supervised_test = as.integer(args[10]) # maximum number of anchors to be tested example, suggested 20000



############## reading in metadata and sample_conversion files #########################
metadata = fread(metadata_file)
sample_name_id_conversion = fread(sample_name_to_id_mapping,header = FALSE)
###############################################################

################################################################
##### select the anchors for the supervised GLM when no specific list of anchors is provided ################
anchors = fread(anchors_file,select = c("anchor", "effect_size_bin", "number_nonzero_samples", "most_freq_target_1", "cnt_most_freq_target_1", "most_freq_target_2", "cnt_most_freq_target_2","avg_hamming_distance_max_target"))
max_sample_num = max(anchors$number_nonzero_samples,na.rm = TRUE)
anchors = anchors[number_nonzero_samples > (max_sample_num * anchor_sample_fraction_cutoff) & avg_hamming_distance_max_target > 5] ## keep only anchors that are in at least the given fraction of samples 
setorder(anchors,-effect_size_bin)
selected_anchors = anchors[1:min(num_anchors_for_supervised_test,nrow(anchors)),]

################################################################
################################################################
system(paste("mkdir ", directory,"/",run_name,"_supervised_metadata",sep="")) # this is the directory for the supervised analysis files
##################################################################################
####### satc_dump for getting counts for the selected anchors ####################
write.table(selected_anchors$anchor,paste(directory, "/",run_name,"_supervised_metadata/", "selected_anchors_GLMnet.txt",sep=""),sep="\t",row.names=FALSE,quote=FALSE,col.names = FALSE)
for (counter in 0:num_bins-1) {
  system(paste(satc_dump_path, paste(" --anchor_list ", paste(directory, "/",run_name,"_supervised_metadata/", "selected_anchors_GLMnet.txt ", sep = ""), satc_dir, "/bin", counter, ".satc ", directory, "/",run_name,"_supervised_metadata/", "satcOut",counter,".tsv ", sep = "")))
}
# now below I read in satcout files generated by satc_dump
satcOut_files = list.files(path = paste(directory,"/",run_name,"_supervised_metadata/",sep=""), pattern = "satcOut")
counts = data.table()
for (counter in 1:length(satcOut_files)) {
  counts = rbind(counts, fread(paste(directory,"/",run_name,"_supervised_metadata/",satcOut_files[counter], sep = ""))) 
  print(counter)
}
setnames(counts,c("V1","V2","V3","V4"),c("sample_id","anchor","target","count"))
###################################################################################
###################################################################################

################# merging counts with metadata #######################
######################################################################
metadata = metadata[,c(1,2)]
names(metadata) = c("sample_name", "group")
metadata = merge(metadata, sample_name_id_conversion, all.x = TRUE, all.y = FALSE, by.x="sample_name", by.y="V1")
metadata = metadata[!is.na(V2)]
counts = merge(counts, metadata, all.x = TRUE, all.y = FALSE, by.x = "sample_id", by.y = "V2")
######################################################################
######################################################################

system(paste("mkdir ", directory,"/",run_name,"_supervised_metadata/plots",sep=""))
GLM_output_dt = data.table() # the data table that will keep glm information for the selected anchors
#############################################################
####### perform GLM for each selected anchor ################
for (counter in 1:nrow(selected_anchors)){
  tryCatch({
    anchor_interest = selected_anchors$anchor[counter]
    counts_anchor = counts[anchor==anchor_interest] # target counts for the selected anchor 
    counts_anchor[,target_count := sum(count),by=target] # compute total counts for each target
    top_two_targets = counts_anchor[!duplicated(target)][order(-target_count)]$target[1:2] # find the top two targets
    counts_anchor = counts_anchor[target %in% top_two_targets]
    
    #counts_anchor[,anchor_count_per_sample:=sum(count),by=paste(anchor,sample_name)]
    counts_anchor[,anchor_count_per_sample:=sum(count),by=list(anchor,sample_name)] #mkokot_TODO: is this fix ok?
    counts_anchor[,fraction:=count/anchor_count_per_sample,by=1:nrow(counts_anchor)] # compute target fraction per sample
    counts_anchor_reshape = reshape(counts_anchor[,list(sample_name,target,fraction,count)], idvar="sample_name", timevar="target", direction="wide")
    names(counts_anchor_reshape) = c("sample_name","target1_frac","target1_count","target2_frac","target2_count")
    counts_anchor_reshape[is.na(target1_frac),target1_frac:=0]
    counts_anchor_reshape[is.na(target2_frac),target2_frac:=0]
    counts_anchor_reshape[is.na(target1_count),target1_count:=0]
    counts_anchor_reshape[is.na(target2_count),target2_count:=0]
    
    sample_names = data.table(counts_anchor_reshape$sample_name)
    sample_names = merge(sample_names,counts_anchor[!duplicated(sample_name),list(sample_name,group)],all.x=TRUE,all.y = FALSE,by.x="V1",by.y="sample_name")
    sample_names[,class:=as.numeric(as.factor(group))] # class is the numeric conversion of the groups which is needed for the multinomnial GLM
    
    counts_anchor_reshape[,sample_name:=NULL]
    
    regression_formula = as.formula( "class ~ target1_frac + target2_frac")
    
    counts_anchor_reshape = cbind(counts_anchor_reshape,sample_names$group,sample_names$class)
    colnames(counts_anchor_reshape)[5] = "group"
    colnames(counts_anchor_reshape)[6] = "class"
    counts_anchor_reshape = counts_anchor_reshape[!is.na(group)] 
    counts_anchor_reshape[,num_per_group:=.N,by=group]
    counts_anchor_reshape[,weight:=1/num_per_group]
    counts_anchor_reshape = counts_anchor_reshape[num_per_group>9]
    
    # below if there is at least two groups for the anchor we perform GLMnet multinomial regression 
    if (length(unique(counts_anchor_reshape$group))>1){
      x_glmnet = model.matrix(regression_formula, counts_anchor_reshape)
      glmnet_model = cv.glmnet(x_glmnet, as.factor(counts_anchor_reshape$group), family = c("multinomial"), intercept = FALSE, alpha = 1, nlambda = 50, nfolds = 5, weights = counts_anchor_reshape$weight)
      glmnet_coeffs = coef(glmnet_model)
      
      largest_GLM_coefficient = max(unlist(lapply(lapply(glmnet_coeffs,abs),max))) # this will give us the GLM coefficient with the highest magnitude
      # if the largest coefficient >1 then we plot target counts fractions and add it to the output table 
      if (largest_GLM_coefficient > 1){
        metadata_group_names = paste(names(glmnet_coeffs), collapse = "||") # collapse all the group names for this into a string
        GLM_coefficients = paste(lapply(glmnet_coeffs, paste, collapse = ":"),collapse = "||") # collapse all the GLM coefficients into a string
        GLM_output_dt_anchor = cbind(selected_anchors[anchor==anchor_interest], metadata_group_names, GLM_coefficients, largest_GLM_coefficient)
        GLM_output_dt = rbind(GLM_output_dt, GLM_output_dt_anchor)
        
        #generate and write boxplot/scatterplot for the anchor
        pdf(file=paste(directory, "/",run_name,"_supervised_metadata/plots/", anchor_interest, ".pdf", sep = ""), width = 8, height = 6)
        g1 = ggplot(counts_anchor_reshape, aes(y = target1_frac, x = as.factor(group), color = as.factor(group))) + geom_boxplot() + theme_bw() +ggtitle(anchor_interest)
        g2 = ggplot(counts_anchor_reshape, aes(x = target1_count, y = target2_count, shape = as.factor(group), color = as.factor(group))) + geom_point() + theme_bw()
        print(grid.arrange(g1, g2, nrow = 2))
        dev.off()
      }
    }
  },error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
write.table(GLM_output_dt, paste(directory,"/",run_name,"_supervised_metadata/GLM_supervised_file.tsv", sep = ""), sep = "\t", row.names = FALSE, quote = FALSE)
######################################################################################
######################################################################################
